use sakila;
#1. List the number of films per category.
#requires a join between category and film_category tables on category_id
SELECT b.category_id, count(*) AS film_count
	FROM film_category as a
    INNER JOIN category as b
    ON a.category_id = b.category_id
    GROUP BY a.category_id;
    
#2.Retrieve the store ID, city, and country for each store.
#requires a join between store and address on address_id
#requires a join between address and city on city_id
#requires a join between city and country on country_id
SELECT store_id, city, country
	FROM store as a
    INNER JOIN address as b
    ON a.address_id = b.address_id
    INNER JOIN city as c
    ON b.city_id=c.city_id
    INNER JOIN country as d
    ON c.country_id=d.country_id;

#3.Calculate the total revenue generated by each store in dollars
SELECT store_id, sum(amount)
	FROM customer as a
    INNER JOIN payment as b
    ON a.customer_id = b.customer_id
    GROUP BY store_id;

#4. Determine the average running time of films for each category
SELECT c.name, ROUND(AVG(length),2) AS average_movie_duration
	FROM film as a
    INNER JOIN film_category as b
    ON a.film_id = b.film_id
    INNER JOIN category as c
    ON b.category_id=c.category_id
    GROUP BY c.name;

